project:
  type: website

website:
  title: "Anaël Lenquette"
  page-navigation: false

format:
  html:
    css: styles.css
    page-layout: full
    toc: false
    theme: none
    title-block-banner: false
    include-in-header: head.html
